
[profile.default]
solc_version = '0.8.27'
evm_version = 'prague'
optimizer = true
optimizer-runs = 200
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache_forge'
fs_permissions = [{ access = "read", path = "./test/bin" }]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[fuzz]
runs = 5000
max_test_rejects = 150000

# Tenderly integration
[tenderly]
project = "${TENDERLY_PROJECT}"
username = "${TENDERLY_USERNAME}"
access_key = "${TENDERLY_ACCESS_KEY}"
